# Generated by Django 4.2.4 on 2023-10-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfprotocolservice',
            name='public_key',
            field=models.TextField(max_length=6000),
        ),
    ]
