# Generated by Django 4.2.4 on 2023-11-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsservice',
            name='down_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='httpservice',
            name='down_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='icmpservice',
            name='down_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tcpservice',
            name='down_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tfprotocolservice',
            name='down_notified',
            field=models.BooleanField(default=False),
        ),
    ]
