# Generated by Django 4.2.4 on 2023-09-08 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestatustcp',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ServiceStatusDNS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_processing_time', models.FloatField(blank=True, null=True)),
                ('is_up', models.CharField(max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.tcpservice')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
