# Generated by Django 4.2.4 on 2023-09-08 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_servicestatustcp_error_message_servicestatusdns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestatusdns',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.dnsservice'),
        ),
    ]
