# Generated by Django 4.2.4 on 2023-10-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_usercontactinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontactinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d/{{user.username}}'),
        ),
    ]
