# Generated by Django 4.2.4 on 2023-09-08 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_servicestatusdns_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icmpservice',
            old_name='dns',
            new_name='dns_ip',
        ),
        migrations.RemoveField(
            model_name='icmpservice',
            name='ip_address',
        ),
    ]
