# Generated by Django 4.2.4 on 2023-09-08 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_rename_dns_icmpservice_dns_ip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStatusICMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_processing_time', models.FloatField(blank=True, null=True)),
                ('is_up', models.CharField(max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.icmpservice')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
