# Generated by Django 4.2.4 on 2023-10-02 04:46

import config.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_profile_delete_usercontactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(upload_to=config.models.user_directory_path_profile),
        ),
    ]
